[2024-07-22T13:31:40.391+0000] {processor.py:153} INFO - Started process (PID=61) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:31:40.392+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:31:40.392+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:31:40.392+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:31:40.401+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:31:40.400+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:31:40.401+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:31:40.417+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.028 seconds
[2024-07-22T13:32:11.299+0000] {processor.py:153} INFO - Started process (PID=117) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:32:11.299+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:32:11.300+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:32:11.300+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:32:11.319+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:32:11.318+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:32:11.319+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:32:11.334+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.037 seconds
[2024-07-22T13:32:41.535+0000] {processor.py:153} INFO - Started process (PID=173) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:32:41.537+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:32:41.537+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:32:41.537+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:32:41.545+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:32:41.544+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:32:41.545+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:32:41.563+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.029 seconds
[2024-07-22T13:33:11.911+0000] {processor.py:153} INFO - Started process (PID=229) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:33:11.911+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:33:11.912+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:33:11.912+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:33:11.917+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:33:11.917+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:33:11.917+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:33:11.933+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.024 seconds
[2024-07-22T13:33:42.133+0000] {processor.py:153} INFO - Started process (PID=285) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:33:42.133+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:33:42.133+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:33:42.133+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:33:42.138+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:33:42.137+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:33:42.138+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:33:42.157+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.026 seconds
[2024-07-22T13:34:12.486+0000] {processor.py:153} INFO - Started process (PID=341) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:34:12.487+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:34:12.489+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:34:12.489+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:34:12.507+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:34:12.497+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:34:12.508+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:34:12.543+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.059 seconds
[2024-07-22T13:34:42.698+0000] {processor.py:153} INFO - Started process (PID=397) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:34:42.699+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:34:42.701+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:34:42.701+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:34:42.708+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:34:42.708+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:34:42.709+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:34:42.723+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.027 seconds
[2024-07-22T13:35:13.013+0000] {processor.py:153} INFO - Started process (PID=453) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:35:13.014+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:35:13.014+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:35:13.014+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:35:13.020+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:35:13.019+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:35:13.020+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:35:13.034+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.022 seconds
[2024-07-22T13:35:43.303+0000] {processor.py:153} INFO - Started process (PID=509) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:35:43.304+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:35:43.304+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:35:43.304+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:35:43.313+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:35:43.313+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:35:43.313+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:35:43.327+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.025 seconds
[2024-07-22T13:36:13.600+0000] {processor.py:153} INFO - Started process (PID=565) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:36:13.601+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:36:13.601+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:36:13.601+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:36:13.607+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:36:13.606+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:36:13.607+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:36:13.623+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.024 seconds
[2024-07-22T13:36:44.108+0000] {processor.py:153} INFO - Started process (PID=621) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:36:44.109+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:36:44.109+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:36:44.109+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:36:44.115+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:36:44.115+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:36:44.115+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:36:44.129+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.023 seconds
[2024-07-22T13:37:14.369+0000] {processor.py:153} INFO - Started process (PID=677) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:37:14.369+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:37:14.370+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:37:14.369+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:37:14.374+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:37:14.373+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:37:14.374+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:37:14.387+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.019 seconds
[2024-07-22T13:37:44.631+0000] {processor.py:153} INFO - Started process (PID=733) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:37:44.631+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:37:44.631+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:37:44.631+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:37:44.637+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:37:44.637+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:37:44.638+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:37:44.649+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.020 seconds
[2024-07-22T13:38:14.884+0000] {processor.py:153} INFO - Started process (PID=789) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:38:14.885+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:38:14.885+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:38:14.885+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:38:14.891+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:38:14.890+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:38:14.891+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:38:14.904+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.022 seconds
[2024-07-22T13:38:45.262+0000] {processor.py:153} INFO - Started process (PID=845) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:38:45.263+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:38:45.264+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:38:45.264+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:38:45.271+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:38:45.270+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:38:45.271+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:38:45.285+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.024 seconds
[2024-07-22T13:39:15.553+0000] {processor.py:153} INFO - Started process (PID=902) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:39:15.554+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:39:15.554+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:39:15.554+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:39:15.560+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:39:15.559+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:39:15.560+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:39:15.573+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.021 seconds
[2024-07-22T13:39:45.867+0000] {processor.py:153} INFO - Started process (PID=958) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:39:45.867+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:39:45.868+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:39:45.868+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:39:45.873+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:39:45.872+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:39:45.873+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:39:45.886+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.021 seconds
[2024-07-22T13:40:16.282+0000] {processor.py:153} INFO - Started process (PID=1013) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:40:16.282+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:40:16.283+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:40:16.283+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:40:16.288+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:40:16.287+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:40:16.288+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:40:16.302+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.022 seconds
[2024-07-22T13:40:46.515+0000] {processor.py:153} INFO - Started process (PID=1069) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:40:46.515+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:40:46.516+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:40:46.516+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:40:46.525+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:40:46.525+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:40:46.525+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:40:46.541+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.028 seconds
[2024-07-22T13:41:16.910+0000] {processor.py:153} INFO - Started process (PID=1125) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:41:16.911+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:41:16.911+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:41:16.911+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:41:16.916+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:41:16.916+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:41:16.916+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:41:16.929+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.020 seconds
[2024-07-22T13:41:47.373+0000] {processor.py:153} INFO - Started process (PID=1188) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:41:47.374+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:41:47.374+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:41:47.374+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:41:47.378+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:41:47.378+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:41:47.379+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:41:47.460+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.088 seconds
[2024-07-22T13:42:17.635+0000] {processor.py:153} INFO - Started process (PID=1244) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:42:17.636+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:42:17.637+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:42:17.636+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:42:17.642+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:42:17.642+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:42:17.643+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:42:17.728+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.096 seconds
[2024-07-22T13:42:47.821+0000] {processor.py:153} INFO - Started process (PID=1300) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:42:47.822+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:42:47.822+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:42:47.822+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:42:47.826+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:42:47.826+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 57
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:42:47.827+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:42:47.926+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.106 seconds
[2024-07-22T13:42:52.244+0000] {processor.py:153} INFO - Started process (PID=1335) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:42:52.245+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:42:52.245+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:42:52.245+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:42:52.257+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:42:52.256+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 58
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:42:52.257+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:42:52.342+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.099 seconds
[2024-07-22T13:43:00.402+0000] {processor.py:153} INFO - Started process (PID=1343) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:43:00.402+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:43:00.403+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:43:00.403+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:43:00.408+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:43:00.407+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 58
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:43:00.408+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:43:00.496+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.096 seconds
[2024-07-22T13:43:30.769+0000] {processor.py:153} INFO - Started process (PID=1398) to work on /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:43:30.770+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/automated_data_cleaning.py for tasks to queue
[2024-07-22T13:43:30.770+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:43:30.770+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:43:30.775+0000] {logging_mixin.py:115} INFO - [2024-07-22T13:43:30.774+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/automated_data_cleaning.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/automated_data_cleaning.py", line 58
    'retries': 1,
            ^
SyntaxError: invalid syntax
[2024-07-22T13:43:30.775+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/automated_data_cleaning.py
[2024-07-22T13:43:30.867+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/automated_data_cleaning.py took 0.100 seconds
